server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: root
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.security: trace